# Generated by Django 5.1 on 2024-09-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseblock',
            name='ExpenseBlockList',
        ),
        migrations.AddField(
            model_name='expenseblock',
            name='expenseLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expenses',
            name='expenseAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ExpenseTracker',
        ),
    ]
