# Generated by Django 5.1 on 2024-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expenseblock_expenseblocklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseblock',
            name='currentTotalExpense',
            field=models.IntegerField(default=0),
        ),
    ]
