# Generated by Django 5.1 on 2024-09-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expenseblock_currenttotalexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
